[project]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
description = "Run glider metrics notebook"
name = "glider_metrics"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
notebook = "jupyter nbclassic"
metrics = "jupyter nbconvert --to notebook --execute glider_metrics.ipynb --output=glider_metrics-output.ipynb"

[dependencies]
python = "3.13.*"
ioos-metrics = ">=0.5.0,<0.6"
nbclassic = ">=1.1.0,<2"
nbconvert = ">=7.16.4,<8"
tabulate = ">=0.9.0,<0.10"
folium = ">=0.19.5,<0.20"
geopandas = ">=1.0.1,<2"
pandas = ">=2.2.3,<3"
