name: Run glider metrics

on:
  issues:
    types: opened

concurrency: 'main'
jobs:
  glider_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: stefanbuck/github-issue-parser@2ea9b35a8c584529ed00891a8f7e41dc46d0441e  # v3.2.1
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/order-pizza.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > glider_metrics.json

      - run: cat glider_metrics.json

      - uses: peter-evans/close-issue@276d7966e389d888f011539a86c8920025ea0626  # v3.0.1
        with:
          comment: All done!
