name: Run glider metrics

on:
  issues:
    types: [labeled]

concurrency: 'main'
jobs:
  glider_metrics:
    if: github.event.label.name == 'run_metrics'
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: stefanbuck/github-issue-parser@2ea9b35a8c584529ed00891a8f7e41dc46d0441e  # v3.2.1
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/query.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > glider_metrics.json
      - uses: prefix-dev/setup-pixi@v0.8.8
      - run: >
          cat glider_metrics.json
          && pixi run metrics

      - name: Close Issue
        run: >
          gh issue comment --body-file glider_metadata_metrics.md "${{ github.event.issue.number }}"
          && gh issue close "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
